name: foodapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  get: ^4.7.2
  lottie: ^3.3.1
  animated_text_kit: ^4.2.3
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  carousel_slider: ^5.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  slide_to_act: ^2.0.2
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  share_plus: ^11.0.0
  action_slider: ^0.7.0
  flutter_rating_bar: ^4.0.1
  flutter_drawer_plus: ^1.1.1
  dash_chat_2: ^0.0.21
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  youtube_player_flutter: ^9.1.1
  url_launcher: ^6.2.5
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.27
  flutter_svg: ^2.2.0
  pinput: ^5.0.1
  local_auth: ^2.3.0
  timeline_tile: ^2.0.0
  razorpay_flutter: ^1.4.0
  intro_screen_onboarding_flutter: ^1.0.0
  geocoding: ^4.0.0
  get_storage: ^2.1.1
  flutter_onboarding_screen: ^2.0.2
  flutter_speed_dial: ^7.0.0
  flutter_zoom_drawer: ^3.2.0
  map_launcher: ^4.0.0
  pull_down_button: ^0.10.2
  deleteable_tile: ^0.0.1-nullsafety.1
  table_calendar: ^3.1.3
  quickalert: ^1.1.0
  flutter_local_notifications: ^19.4.1
  android_intent_plus: ^5.3.1
  font_awesome_flutter: ^10.9.1
  animations: ^2.0.11
  flutter_login: ^5.1.0
  shared_preferences: ^2.5.3
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/sknapplogo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/sknapplogo.png"


# flutter_native_splash:
#   color: "#ffffff"  
#   image: assets/images/applogologo.png
#   android: true
#   ios: true
#   android_gravity: center
#   ios_content_mode: scaleAspectFit




  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\images\Pizzaloading.json
    - assets\images\
    - assets\images\Success.json
    - assets\images\Failed.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
