name: foodapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  get: ^4.7.2
  lottie: ^3.3.1
  animated_text_kit: ^4.2.3
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  carousel_slider: ^5.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  slide_to_act: ^2.0.2
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  share_plus: ^11.0.0
  action_slider: ^0.7.0
  flutter_rating_bar: ^4.0.1
  flutter_drawer_plus: ^1.1.1
  dash_chat_2: ^0.0.21
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  youtube_player_flutter: ^9.1.1
  url_launcher: ^6.2.5
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.27
  flutter_svg: ^2.2.0
  pinput: ^5.0.1
  local_auth: ^2.3.0
  timeline_tile: ^2.0.0
  razorpay_flutter: ^1.4.0
  intro_screen_onboarding_flutter: ^1.0.0
  geocoding: ^4.0.0
  get_storage: ^2.1.1
  flutter_onboarding_screen: ^2.0.2
  flutter_speed_dial: ^7.0.0
  flutter_zoom_drawer: ^3.2.0
  map_launcher: ^4.0.0
  pull_down_button: ^0.10.2
  deleteable_tile: ^0.0.1-nullsafety.1
  table_calendar: ^3.1.3
  quickalert: ^1.1.0
  flutter_local_notifications: ^19.4.1
  android_intent_plus: ^5.3.1
  font_awesome_flutter: ^10.9.1
  animations: ^2.0.11
  flutter_login: ^5.1.0
  shared_preferences: ^2.5.3
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/sknapplogo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/sknapplogo.png"


# flutter_native_splash:
#   color: "#ffffff"  
#   image: assets/images/applogologo.png
#   android: true
#   ios: true
#   android_gravity: center
#   ios_content_mode: scaleAspectFit




  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\images\Pizzaloading.json
    - assets/images/applogologo.png
    - assets\images\on1.png
    - assets/images/on2.png
    - assets\images\ch1.png
    - assets/images/ch2.png
    - assets\images\ch3.png
    - assets/images/ch4.png
    - assets\images\b1.png
    - assets\images\b2.png
    - assets\images\b3.png
    - assets\images\profile1.jpg
    - assets\images\food1.jpg
    - assets\images\food2.jpeg
    - assets\images\food3.avif
    - assets\images\food4.avif
    - assets\images\food5.jpg
    - assets\images\iconsbike.png
    - assets\images\loctionicons.jpg
    - assets\images\aboutpage.png
    - assets\images\Order completed.json
    - assets\images\mobileimg.jpg
    - assets\images\opt2.png
    - assets\images\opt3.png
    - assets/images/Feedback.json
    - assets\images\p1.png
    - assets\images\p2.png
    - assets\images\P3.png
    - assets\images\p5.png
    - assets\images\p6.png
    - assets\images\p7.png
    - assets\images\bb1.png
    - assets\images\bb3.png
    - assets\images\pro1.jpg
    - assets\images\Delivery.json
    - assets\images\apple.png
    - assets\images\banana.png
    - assets\images\mango.png
    - assets/images/orangee.png
    - assets\images\Pomegranate.png
    - assets\images\grapesblack.png
    - assets\images\papaya.png
    - assets\images\Watermelon.png
    - assets\images\Muskmelon.png
    - assets\images\Pineapple.png
    - assets\images\Guava.png
    - assets\images\sapota.png
    - assets\images\Custard apple.png
    - assets\images\Jackfruit.png
    - assets\images\Dragon fruit.png
    - assets\images\Kiwi.png
    - assets\images\Strawberry.png
    - assets\images\Blueberry.png
    - assets\images\Lychee.png
    - assets\images\pear.png
    - assets\images\Plum.png
    - assets\images\Peach.png
    - assets\images\Apricot.png
    - assets\images\Fig.png
    - assets\images\Avocado.png
    - assets/images/Sweetlime.png
    - assets\images\Lemon.png
    - assets\images\Gooseberry.png
    - assets\images\Ber.png
    - assets\images\Woodapple.png
    - assets\images\Starfruit.png
    - assets\images\Jamun.png
    - assets\images\Tamarind.png
    - assets\images\Coconut.png
    - assets\images\Dates.png
    - assets\images\Rambutan.png
    - assets\images\Mangosteen.png
    - assets\images\Roseapple.png
    - assets\images\notifications .png
    - assets\images\Indian blackberry.png
    - assets\images\Cherry.png
    - assets\images\Tomato.png
    - assets\images\Potato.png
    - assets\images\Onion.png
    - assets\images\Brinjal.png
    - assets\images\Carrot.png
    - assets\images\Beetroot.png
    - assets\images\Cabbage.png
    - assets\images\Cauliflower.png
    - assets\images\Greenbeans.png
    - assets\images\Bottlegourd.png
    - assets\images\Ridgegourd.png
    - assets\images\Bittergourd.png
    - assets\images\Snakegourd.png
    - assets\images\Drumstick.png
    - assets\images\Ladyâ€™sfinger.png
    - assets\images\Capsicum.png
    - assets\images\Spinach (Palak.png
    - assets\images\Greenpeas.png
    - assets\images\Corianderleaves.png
    - assets\images\Mintleaves.png
    - assets\images\Springonion.png
    - assets\images\Turnip.png
    - assets\images\Knolkhol.png
    - assets\images\Ashgourd.png
    - assets\images\Pumpkin.png
    - assets\images\Rawbanana.png
    - assets\images\Rawmango.png
    - assets\images\Taroroot.png
    - assets\images\Yam.png
    - assets\images\Cluster beans.png
    - assets\images\Broad beans.png
    - assets\images\Colocasia leaves.png
    - assets\images\Mustard greens.png
    - assets\images\Fenugreek leaves.png
    - assets\images\Dill leaves.png
    - assets\images\Raw jackfruit.png
    - assets\images\Sweet corn.png
    - assets\images\Cucumber.png
    - assets\images\Radish.png
    - assets\images\Vanilla Cup.png
    - assets\images\Strawberry Cup.png
    - assets\images\Chocolate Cup.png
    - assets\images\Butterscotch Cup.png
    - assets\images\mango.png
    - assets\images\Pista Cup.png
    - assets\images\Black Currant Cup.png
    - assets\images\Kesar Pista Cup.png
    - assets\images\American Nuts Cup.png
    - assets\images\Mango Cups.png
    - assets\images\Pista Cups.png
    - assets\images\Kulfi Cupasss.png
    - assets\images\Choco Cones.png
    - assets\images\Butterscotch Coness.png
    - assets\images\Double Chocolate Cone.png
    - assets\images\Rajbhog Cone.png
    - assets\images\Paan Cone.png
    - assets\images\Black Forest Conesss.png
    - assets\images\Mango Conesssssss.png
    - assets\images\Choco Vanilla Conenenes.png
    - assets\images\Nutty Choco Conesssss.png
    - assets\images\Pista Cups.png
    - assets\images\Pista Cupsesesepista.png
    - assets\images\notificationsssssssss.png
    - assets\images\Delete.json
    - assets\images\Chocobarsss.png
    - assets\images\Mango Dolly.png
    - assets\images\Orange Sticksss.png
    - assets\images\Raspberry Stickss.png
    - assets\images\Pineapple Stickss.png
    - assets\images\Kulfi Stickses.png
    - assets\images\Chocolate Nutty Stickss.png
    - assets\images\Ice Apple Stickes.png
    - assets\images\Litchi Stickes.png
    - assets\images\Grape Stickes.png
    - assets\images\Vanilla Family Packes.png
    - assets\images\ch Family Packes.png
    - assets\images\Butterscotch Family Packes.png
    - assets\images\Mango Family Packes.png
    - assets\images\Black Currant Family Packeses.png
    - assets\images\Kesar Pista Family Packes.png
    - assets\images\American Nuts Family Pack.png
    - assets\images\Rajbhog Family Packes.jpg
    - assets\images\Sitaphal (Custard Apple) Family Pack.png
    - assets\images\Royal Rajbhog Family Packes.png
    - assets\images\cookingdariy.png
    - assets\images\cooking2.png
    - assets\images\cooking3.png
    - assets\images\cookingfinish.png
    - assets\images\phonenumber.png
    - assets\images\optscrreennn.png
    - assets\images\addtotot.png
    - assets\images\favtourite.png
    - assets\images\favtouriteesese.png
    - assets\images\warining.json
    - assets\images\fingerrorint.json
    - assets\images\Fresh Organic Carrot.png
    - assets\images\Green Capsicum.png
    - assets\images\Tomato (500g).png
    - assets\images\Potato (1kg).png
    - assets\images\banner1.png
    - assets\images\banner4.jpg
    - assets\images\banner2.png
    - assets\images\give order.json
    - assets\images\SKNLOGO.png
    - assets\images\optvega.jpg
    - assets\images\phonebg.jpg
    - assets\images\comment.json
    - assets\images\maplocationlogo.png
    - assets\images\Confetti.json
    - assets\images\orderhistorylogo.png
    - assets\images\Error animation.json
    - assets\images\Bisleriwater4.jpg
    - assets\images\Bisleriwater1.png
    - assets\images\Bisleriwater4.jpg
    - assets\images\Bisleriwater5.jpg
    - assets\images\Bisleriwater6.jpg
    - assets\images\Bisleriwater7.jpg
    - assets\images\cartegories.png
    - assets\images\cartegories1.png
    - assets\images\cartegories2.png
    - assets\images\cartegories3.png
    - assets\images\cartegories4.png
    - assets\images\cartegories5.png
    - assets\images\cartegories6.png
    - assets\images\phonescreenpng.jpg
    - assets\images\fruitsimges.jpg
    - assets\images\optscreennnnnn.jpg
    - assets\images\onboscreen2.jpg
    - assets\images\onboscreen1.jpg
    - assets\images\onboscreen3.jpg
    - assets\images\onboscreen4.jpg
    - assets\images\googlemapicons.png
    - assets\images\Bisleri8.png
    - assets\images\Bisleriwater9.jpg
    - assets\images\registerpage.jpg
    - assets\images\Success.json
    - assets\images\Failed.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
